set(PALABOS_ROOT "/home/jifutan/insituBloodFlow/src/palabos" CACHE STRING "")
set(BLOODFLOW_ROOT "/home/jifutan/insituBloodFlow/BloodFlowTan" CACHE STRING "")
set(LAMMPS_DIR "/home/jifutan/insituBloodFlow/src/lammps" CACHE STRING "")
set(SENSEI_DIR "/home/jifutan/insituBloodFlow/install/SENSEI/lib/cmake" CACHE STRING "")
set(CMAKE_C_COMPILER "mpicc" CACHE STRING "Specify the compiler to use")
set(CMAKE_CXX_STANDARD "11" CACHE STRING "Using c++11 version")
